name: repo_generator
description: Dart package to generate repositories using retrofit clients
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  build: ^2.3.1
  built_collection: ^5.1.1
  code_builder: ^4.4.0
  meta: ^1.9.1
  source_gen: ^1.4.0

dev_dependencies:
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^5.1.0
